// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    InternalGame: typeof import('./src/components/InternalGame.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}

export { }
