import { uniqueId } from 'lodash'

/** 其他 */
export const others: Work.OtherWork[] = [
  {
    id: uniqueId(),
    name: '越经纪',
    types: ['Web', '微信小程序'],
    desc: '越服经纪楼盘维护、客户管理、带看上访、渠道管理、佣金结算、提成统计、新房报备等环节的数字化工具。',
    technologyList: [
      'Vue3',
      'Pinia',
      'Vite',
      'TypeScript',
      'Sass',
      'Element Plus',
      'Axios',
      '微信小程序',
      'uni-app',
    ],
  },
  {
    id: uniqueId(),
    name: '数据魔方',
    types: ['Web'],
    desc: '越秀房宝/CDP数据自助筛选平台，允许用户一次性针对多个数据集进行筛选及提取审核，解决现在提取方案存在的流程长、耗时长、效率低等问题。',
    technologyList: ['Vue3', 'Pinia', 'Vite', 'TypeScript', 'Sass', 'Element Plus', 'Axios'],
  },
  {
    id: uniqueId(),
    name: '越秀商城',
    types: ['Web', 'H5'],
    desc: '越秀地产线上商城，提供公司周边产品的展示及购买功能。支持接入到悦秀会 App、悦秀会公众号、悦享会小程序等多个渠道。',
    technologyList: [
      'Vue2',
      'Vuex',
      'Vue CLI',
      'JavaScript',
      'Sass',
      'Element UI',
      'Axios',
      'Webpack',
      '微信公众号',
    ],
  },
  {
    id: uniqueId(),
    name: 'TDM数据管理平台',
    types: ['Web'],
    desc: '吉利汽车研发数据管理平台。',
    technologyList: ['Vue3', 'Pinia', 'Vite', 'TypeScript', 'Sass', 'Element Plus', 'Axios'],
  },
  {
    id: uniqueId(),
    name: '伊智商城',
    types: ['Web', '微信小游戏', 'H5'],
    desc: '伊智科技 Sass 商城，支持分销、拼团、秒杀、抽奖等多种营销工具，支持商城自定义装修。',
    technologyList: ['Taro', 'React', 'JavaScript', 'Sass', 'Axios', '微信小程序', '支付宝小程序'],
  },
  {
    id: uniqueId(),
    name: '伊智OA',
    types: ['H5'],
    desc: '为伊智顾问部门开发的移动端 H5 办公协作软件。',
    technologyList: ['React', 'Antd Mobile', 'JavaScript', 'Sass', 'Axios'],
  },
  {
    id: uniqueId(),
    name: '伊智商家版',
    types: ['Android', 'iOS', 'H5'],
    desc: '智慧门店经营工具，助力客户管理、员工成长及经营效率提升，实现智慧门店轻松增长。',
    technologyList: ['Android', 'React', 'Antd Mobile', 'JavaScript', 'Sass', 'Axios'],
  },
  {
    id: uniqueId(),
    name: '伊智大掌柜',
    types: ['Android', 'H5'],
    desc: '专为美业门店设计的收银一体机系统，简洁易用的收银操作系统界面，完整的会员数据查询功能，取代传统纸质水单实现无纸化，与PC端、手机端实时同步数据，老板可随时随地掌握门店营业情况，让门店经营变得高效简单。',
    technologyList: ['Android', 'React', 'Antd Mobile', 'JavaScript', 'Sass', 'Axios'],
  },
  {
    id: uniqueId(),
    name: '数钱大战',
    types: ['微信小游戏'],
    desc: '数字闯关类小游戏。',
    technologyList: [
      'JavaScript',
      'Cocos Creator',
      '小程序云开发',
      '小程序开放数据域',
      '小游戏排行榜',
    ],
  },
  {
    id: uniqueId(),
    name: '任务整合清单',
    types: ['Android', 'iOS'],
    desc: '使用 Flutter 开发的一款任务清单应用，支持任务分类、提醒、优先级设置等功能，帮助用户更好地管理和完成任务。',
    technologyList: ['Flutter', 'Dart', 'Android', 'iOS'],
  },
]
